### ISSUE TITLE
How can I modify patient name or some value of tag?

### ISSUE THREAD

**Issue by huyle73** [project-eutopia/vega#15]

**Comment by project-eutopia** [comment]
Hello @huyle73, thanks for asking this question. Are you modifying the patient name of an existing DICOM file, or building a new one from scratch? If you just want to modify one to change a name, here is a quick snippet that should work (I tested locally that it does indeed create a new DICOM file with the name set to "John^Smith"):

```cpp
#include <cstdlib>
#include <string>

#include "vega/dictionary/dictionary.h"
#include "vega/dicom/file.h"

int main(int argc, char *argv[]) {
  vega::dicom::File file(argv[1]);

  auto manipulator = file.data_set()->element<vega::dictionary::PatientName>()->manipulator();
  for (auto& name : *manipulator) {
    name = "John^Smith";
  }

  file.write(argv[2]);
  return 0;
}
```

The `manipulator` method returns a pointer to a class that can be used to modify the content of a data element. For instance, the [PersonNameManipulator](https://github.com/project-eutopia/vega/blob/c7b536c5e949094a908fa8f378729dbffc657f4a/include/vega/manipulators/person_name_manipulator.h#L8) is an subclass of the PaddedStringManipulator which acts like a [std::vector in many ways](https://github.com/project-eutopia/vega/blob/c7b536c5e949094a908fa8f378729dbffc657f4a/include/vega/manipulators/padded_string_manipulator.h#L89-L114). That is why in this snippet I can run a for-loop over each name in the PatientName data element and modify it in place. If you know there will only ever be one element, then you could also just do:

```cpp
manipulator->at(0) = "John^Smith";
```

Each other type of tag also has associated manipulators that basically act as a std::vector of the underlying types (e.g. IntegerStringManipulator is basically a std::vector<int32_t>). Does this help, or do you have any specific use cases that you are interested in that would benefit from some improved documentation?

**Comment by huyle73** [comment]
Thanks for your reply. But I have a problem that when I run your snippets and I have some error. The reason is that I just want to modify patient name or some values in just previous dicom image? Can you give me a solution?

**Comment by huyle73** [comment]
This is my error:
terminate called after throwing an instance of 'vega::dicom::Reader::ReadingError'
  what():  Reader page does not allow VR: xs (0x7378), tag: (0028,0120) for PixelPaddingValue
Aborted (core dumped)

**Comment by huyle73** [comment]
And I have a question? Do I need to write a file for saving the change?

**Comment by huyle73** [comment]
I run your code but the patient name not change. Can you give me a solution on this code?
`#include <cstdlib>
#include <string>

#include "vega/dictionary/dictionary.h"
#include "vega/dicom/file.h"
using namespace std;
int main(int argc, char *argv[]) {
//vega::dictionary::Dictionary::set_dictionary("/usr/local/share/vega/dictionary.txt");
  const string file_name = "/home/huyle/Desktop/vega/test/data/undefined_SQ_rtdose.dcm";
  vega::dicom::File file(file_name);

  auto manipulator = file.data_set()->element<vega::dictionary::PatientName>()->manipulator();
  for (auto& name : *manipulator) {
    name = "abcdefgh";
  }

//   manipulator->at(0) = "John^Smith";


  file.write("/home/huyle/Desktop/dataset/a/undefined_SQ_rtdose.dcm.dcm");
  return 0;
}`

**Comment by huyle73** [comment]
Thank you for your helpful advice!
